version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - run: yarn test:ci
  build-master:
    filters:
      branches:
        only:
          - master
    - run:
      name: release
      command: yarn release --yes
  build-next:
    filters:
      branches:
        only:
          - next
    - run:
      name: prerelease
      command: yarn prerelease --yes
