version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10-alpine
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Installing NPM Dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths: .
      - run:
          name: Run Unit & Integration Tests
          command: yarn test:ci
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
  deploy-prod:
    docker:
      - image: circleci/node:10-alpine
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Publishing Release
          command: yarn release --yes
  deploy-dev:
    docker:
      - image: circleci/node:10-alpine
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Publishing Prerelease
          command: yarn prerelease --yes

workflows:
  my_workflow:
    jobs:
      - build
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: next
