version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Installing NPM Dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Build
          command: yarn build
      - run:
          name: Run Unit & Integration Tests
          command: yarn test:ci
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
  publish:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Publishing Release
          command: yarn release --yes
  publish-next:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Publishing Prerelease
          command: yarn prerelease --yes

workflows:
  my_workflow:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
      - publish-next:
          requires:
            - build
          filters:
            branches:
              only: next
