version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    branches:
      only:
        - master
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Building
          command: yarn build
      - run:
          name: Testing
          command: yarn test:ci
      # - run: yarn release --yes
      - run: echo "Running pipeline on master"
