version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'eb:f6:49:b3:3a:2a:5d:a8:98:86:4b:22:3f:1f:d2:e5'
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Installing NPM Dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths: .
      - run:
          name: Run Unit & Integration Tests
          command: yarn test:ci
      - store_test_results:
          path: tests/test-results
      - store_artifacts:
          path: test-results
  release:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Publishing Release
          command: yarn release --yes
  prerelease:
    docker:
      - image: circleci/node:12
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Publishing Prerelease
          command: yarn prerelease --yes

workflows:
  my_workflow:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
      - prerelease:
          requires:
            - build
          filters:
            branches:
              only: next
